services:
  app-prod:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${PROD_IMAGE_TAG}
    container_name: zerost-prod
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "8080:8080"

  app-dev:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${DEV_IMAGE_TAG}
    container_name: zerost-dev
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - "8081:8080"
