spring:
  config:
    activate:
      on-profile: dev

  mvc:
    log-resolved-exception: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO
    com.zerost.api: INFO
    org.springdoc: ERROR
    org.springframework.web.servlet.DispatcherServlet: WARN
    org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration: ERROR
    org.springframework.security: WARN
    org.hibernate.orm.deprecation: ERROR
